Feature/delete book
az879593/nccu_dbms pull request #17
Opened 2024-12-25 03:39 UTC by ycyueh

- Test
call API: POST http://127.0.0.1:5000/api/v1/post/add_post
Body:
`
{
    "seller_user_id": 1, 
    "book_id": 101, 
    "book_condition": "new", 
    "price": 330
}
`
先新增一則貼文，post_id = 1
![image](https://github.com/user-attachments/assets/9f262113-f02d-4e6f-946a-5cbd19eaba5d)

再測試delete 有無成功
call API: POST http://127.0.0.1:5000/api/v1/post/delete_post/1

![image](https://github.com/user-attachments/assets/75ba9e62-b3eb-4998-9501-1b7e8f630c97)

若無此篇貼文，post_id = 2
call API: POST http://127.0.0.1:5000/api/v1/post/delete_post/2

![image](https://github.com/user-attachments/assets/40bb5c8e-3cfe-4750-a6b0-b864f817e583)

2025-01-04 15:33 UTC, JLin056 requested changes

2025-01-04 15:33 UTC, JLin056 commented on backend/src/app/services/post_service.py
> +                "seller_user_id": post[1]  # 假設第二個欄位是 title
這個註解是錯的！

2025-01-04 15:44 UTC, JLin056 commented
![image](https://github.com/user-attachments/assets/d68697e1-8c3f-4cd8-9c66-7cf1bc7092d1)
這一部分可能要等 其他內容可以輸入，再測看看！

2025-01-04 15:44 UTC, JLin056 requested changes

2025-01-04 15:44 UTC, JLin056 commented on backend/src/app/services/book_service.py
> +            )
這樣的寫法 其他的欄位要填，會填不進去！
<img width="809" alt="image" src="https://github.com/user-attachments/assets/a34ce8f3-c903-47f5-8878-718a190d6da9" />

2025-01-04 16:23 UTC, JLin056 commented on backend/src/app/schema.sql
>  );
這個當初先把 not null 註解掉是為了開發方便哈哈
會影響到你後續的邏輯嗎？如果不會可以維持原本

2025-01-05 02:02 UTC, ycyueh commented on src/app/database.py
> +    with open(schema_path, 'r', encoding='utf-8') as f:
可以跑，我刪除 utf-8 設定

2025-01-05 02:02 UTC, ycyueh commented on backend/src/app/services/post_service.py
> +                "seller_user_id": post[1]  # 假設第二個欄位是 title
solve!

2025-01-05 02:08 UTC, ycyueh commented on backend/src/app/services/book_service.py
> +            )
改成輸入 (book_name,ISBN,author,version,public_year)

2025-01-06 03:44 UTC, closed without merging